version: '3.4'

services:
  influxdb:
    image: influxdb:1.8

    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:latest

    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./k6-load-testing-results_rev3.json:/var/lib/grafana/dashboards/k6-load-testing-results_rev3.json
  k6:
    image: loadimpact/k6:latest
    command: run /scripts/test_cs_service.js
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6

    volumes:
      - ../scripts:/scripts